### ISSUE TITLE
Make Events Dynamic

### ISSUE THREAD

**Issue by kaushalvivek** [kaushalvivek/E-Cell#5]

**Comment by kaushalvivek** [comment]
Use expandable cards, instead of the current layout.

**Comment by zubairabid** [comment]
About halfway through this.

Not changing the "Upcoming events (Megathon)" just yet.

**Comment by zubairabid** [comment]
About halfway through this.

Not changing the "Upcoming events (Megathon)" just yet.

**Comment by 500swapnil** [comment]
Solved in #12
