### ISSUE TITLE
Make Partnerships and Associates Dynamic

### ISSUE THREAD

**Issue by kaushalvivek** [kaushalvivek/E-Cell#8]

**Comment by surana-mudit** [comment]
@kaushalvivek  can you explain a bit more about how to make them dynamic?

**Comment by kaushalvivek** [comment]
@surana-mudit , as you can see on the team page, content is rendered from backend, with basic template to render in html. What you'll need to do:

- Create a new model in models.py for Associates
- Use template to render in the html file similar to team
- Add the content for the model in database

[This](https://tutorial.djangogirls.org/en/dynamic_data_in_templates/) can be useful.
@mridulnagpal coded the initial models, he'll be available if you need any help.

**Comment by surana-mudit** [comment]
working on it
